#!/usr/bin/env python3
"""
Generate 18 PLUMED window files для US run.

Spec (physicist consilium v2):
  - CV = min(d_FeH), 18 windows
  - d_FeH ∈ [1.5, 4.0] Å, spacing 0.15 Å (close to physicist 0.13 with even count)
  - K = 1000 kJ/mol/Å² → 100,000 kJ/mol/nm² in PLUMED native nm
  - σ_window = √(kT/K) = 0.05 Å
  - spacing/σ = 3.0 (Gaussian overlap для WHAM)

Output: infra/us_protocol/windows/window_NN/plumed.dat (NN = 00..17)
"""
import argparse
from pathlib import Path

# Window centers (Angstrom)
WINDOW_CENTERS_A = [1.50, 1.65, 1.80, 1.95, 2.10, 2.25, 2.40, 2.55,
                   2.70, 2.85, 3.00, 3.15, 3.30, 3.45, 3.60, 3.75,
                   3.90, 4.00]
KAPPA_KJ_MOL_A2 = 1000.0

# s138 evening physicist Patch P3: pre-eq ramp parameters для MOVINGRESTRAINT.
# AT_INIT — initial CV before ramp (default 1.72 A = Fe-H bond state per nearest_h38.py s138 verdict).
# KAPPA_INIT — soft start (10% final) prevents violent initial kick (5.5 eV/A → 0.55 eV/A).
AT_INIT_A = 1.72
KAPPA_INIT_FRACTION = 0.1  # 10% final K = 100 kJ/mol/A^2 soft start


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--template", default="plumed_window_template.dat")
    ap.add_argument("--out-dir", default="windows")
    ap.add_argument("--at-init-a", type=float, default=AT_INIT_A,
                    help="Initial CV (A) для MOVINGRESTRAINT ramp (default: 1.72 A Fe-H state)")
    ap.add_argument("--kappa-init-fraction", type=float, default=KAPPA_INIT_FRACTION,
                    help="Initial K fraction (0..1) для soft ramp start (default: 0.1)")
    args = ap.parse_args()

    template_path = Path(args.template)
    out_root = Path(args.out_dir)
    out_root.mkdir(parents=True, exist_ok=True)

    template = template_path.read_text()
    at_init_nm = args.at_init_a / 10.0
    kappa_init_nm = KAPPA_KJ_MOL_A2 * 100.0 * args.kappa_init_fraction

    for i, center_a in enumerate(WINDOW_CENTERS_A):
        center_nm = center_a / 10.0
        kappa_nm = KAPPA_KJ_MOL_A2 * 100.0  # kJ/mol/Å² × 100 = kJ/mol/nm²

        win_dir = out_root / f"window_{i:02d}"
        win_dir.mkdir(exist_ok=True)

        plumed_dat = (template
                      .replace("{AT_VALUE_NM_INIT}", f"{at_init_nm:.4f}")
                      .replace("{KAPPA_NM2_INIT}", f"{kappa_init_nm:.1f}")
                      .replace("{AT_VALUE_NM}", f"{center_nm:.4f}")
                      .replace("{KAPPA_NM2}", f"{kappa_nm:.1f}")
                      .replace("{WINDOW_ID}", f"{i:02d}"))

        (win_dir / "plumed.dat").write_text(plumed_dat)

        print(f"  Window {i:02d}: d_FeH = {center_a:.2f} Å ({center_nm:.4f} nm), "
              f"ramp from {args.at_init_a:.2f} A K_init={kappa_init_nm:.0f} → "
              f"K_final={kappa_nm:.0f} → {win_dir}/plumed.dat")

    # Manifest
    manifest = "# Window manifest (US protocol W2 paper #1)\n"
    manifest += "# Generated by generate_windows.py\n"
    manifest += f"# Total: {len(WINDOW_CENTERS_A)} windows\n\n"
    manifest += "# window_id  d_FeH_A  d_FeH_nm  K_kJ_mol_A2\n"
    for i, c_a in enumerate(WINDOW_CENTERS_A):
        manifest += f"{i:02d}  {c_a:.2f}  {c_a/10:.4f}  {KAPPA_KJ_MOL_A2:.0f}\n"
    (out_root / "manifest.txt").write_text(manifest)

    print(f"\n  Total windows: {len(WINDOW_CENTERS_A)}")
    print(f"  Manifest: {out_root}/manifest.txt")


if __name__ == "__main__":
    main()
